#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

touch foam.foam
runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication checkMesh

runApplication setFields

runApplication decomposePar

runApplication mpirun -np 4 interFoam -parallel

# runApplication $(getApplication)

#------------------------------------------------------------------------------
